Logger:
    SyncTimeout: 75ms
    Cores:
    - Name : stderr
      EncoderLevel: development
      Path: /dev/stderr
      Level : 0
    - Name : logfile
      EncoderLevel: production
      Path: "../tmp/log"
      Level : -1
HTTPServer:
  Address: localhost:8080
  IdleTimeout: 10s
