Logger:
    SyncTimeout: 1s 
    Cores:
    - Name : stderr
      EncoderLevel: production
      Path: /dev/stderr
      Level : 0
      MustCreateCore: false
    - Name : logfile
      EncoderLevel: production
      Path: "${WORKSPACE}/tmp/log.log"
      Level : -1
      MustCreateCore: true