Logger:
    Cores:
    - Name : stderr
      EncoderLevel: production
      Path: /dev/stderr
      Level : 0
    - Name : logfile
      EncoderLevel: production
      Path: "./zap.log"
      Level : -1