Logger:
    SyncTimeout: 1s 
    Cores:
    - Name : stderr
      EncoderLevel: production
      Path: /dev/stderr
      Level : 0
      MustCreateCore: false
    - Name : logfile
      EncoderLevel: production
      Path: "${WORKSPACE}/tmp/log.log"
      Level : -1
      MustCreateCore: true
HTTPServer:
  ListeningAddress: localhost
  Port: :7731
Kafka:
  Addresses:
  - localhost:9092
  - localhost:9093
  - localhost:29092